name: auto-merge

permissions: {}

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      merge-method:
        default: squash
        description: 'merge method'
        options:
          - squash
          - rebase
        required: false
        type: choice
      pr-number:
        description: 'single pr number'
        required: false
        type: string

concurrency:
  cancel-in-progress: true
  group: auto-merge-dispatch

jobs:
  auto-merge:
    permissions:
      checks: read
      contents: write
      pull-requests: write
      statuses: read
    uses: escapace/workflows/.github/workflows/auto-merge.yaml@trunk
    with:
      merge-method: ${{ inputs.merge-method }}
      pr-number: ${{ inputs.pr-number }}
