name: ci

on:
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: read

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: ref
        id: ref
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "value=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          else
            echo "value=${GITHUB_REF}" >> $GITHUB_OUTPUT
          fi
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.ref.outputs.value }}
      - id: action-context
        uses: ./
        with:
          token: ${{ github.token }}
