name: ci

on:
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: read

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.head_ref || github.ref }}
      - id: action-context
        uses: ./
        with:
          token: ${{ github.token }}
